
services:
  k3s-master:
    build:
      context: .
      dockerfile: Containerfile
      args:
        HOSTNAME: "k8smaster"
        K3S_TOKEN: "jDVP0xoUHfawYDyU"
        SSH_PUBLIC_KEY: "your public key"
        K8S_VERSION: "1.30.1"
    image: k3s-master-bootc:latest
    container_name: k3s-master
    privileged: true
    network_mode: "bridge"
    ports:
      - "6443:6443"
      - "10250:10250"
      - "2379-2380:2379-2380"
    environment:
      - K3S_TOKEN=jDVP0xoUHfawYDyU
    restart: unless-stopped
